services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883'

  timescaledb:
    image: timescale/timescaledb:2.23.0-pg18
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      POSTGRES_DB: telemetry
    ports:
      - '5432:5432'

  devices-simulator:
    build:
      context: ./Devices-Simulator
    depends_on:
      - mosquitto