services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883'

  timescaledb:
    image: timescale/timescaledb:2.23.0-pg18
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry
      POSTGRES_DB: telemetry
    ports:
      - '5432:5432'

  devices-simulator:
    build:
      context: ./Devices-Simulator
    environment:
      MQTT_URL: mqtt://mosquitto:1883
    depends_on:
      - mosquitto

  backend:
      build:
        context: ./Backend
      environment:
        MQTT_URL: mqtt://mosquitto:1883
        DATABASE_URL: postgres://telemetry:telemetry@timescaledb:5432/telemetry
        PORT: 3000
      ports:
        - '3000:3000'
      depends_on:
        - mosquitto
        - timescaledb

  frontend:
    build:
      context: ./Frontend
    ports:
      - '4200:80'
    depends_on:
      - backend